### ISSUE TITLE
Provide option to make `props` render into their own section.

### ISSUE THREAD

**Issue by allanhortle** [dxinteractive/jsdonk#13]
Just to make it easier for the reader So they can scan for the propTypes section

**Comment by dxinteractive** [comment]
Lets set our own reacty jsdoc tags, like `@props` for received props and `@childprops` for props passed to children?

http://stackoverflow.com/questions/14982923/how-to-add-and-use-a-tag-on-jsdoc

**Comment by dxinteractive** [comment]
`@prop` implemented on `feature/react-tags` branch. Need to config markdown plugin to use it, and need to implement `@childprops`.
